/* 
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

*/
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        // 定义一个字符 赋值0
        char c = 0;
        // 利用异或的特性, 清除所有相同的值
        // 利用0异或值x, 结果都为 x
        for (int i = 0; i < s.length(); i++)
        {
            c = c ^ s[i];
            c = c ^ t[i];
        }
        c = c ^ t.back();

        return c;
    }
};